### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Manliketjb** [CQC-Scripting/cqc-mugshot#7]
Seems to not be working for me, I've reconfigured it to work for Gabz MRPD but can't get it working, no 3rd eye interaction or anything, the test command isn't even working. Used Debug for the boxzone and it's in the right spot

**Comment by Intelligentzombie29** [comment]
Config = {}

Config.Webhook = 'your webhook to discord' -- Images will be uploaded here
Config.TestCommand = true -- Use this when testing /testmugshot

Config.CustomMLO = true -- If you use a MLO use the options below to change the camera location. Otherwise it will use the default IPL for the mugshot location
Config.MugshotLocation = vector3(472.78, -1011.18, 25.27) -- Location of the Suspect
Config.MugshotSuspectHeading = 176.6 -- Direction Suspsect is facing
Config.MugShotCamera = {
    x = 473.0,
    y = -1012.59,
    z = 26.27,
    r = {x = 0.0, y = 0.0, z = 352.84} -- To change the rotation use the z. Others are if you want rotation on other axis
}

Config.BoardHeader = "Los Santos Police Department" -- Header that appears on the board
Config.WaitTime = 2000 -- Time before and after the photo is taken. Decreasing this value might result in some angles being skiped.
Config.Photos = 3 -- Front, Back Side. Use 4 for both sides
Config.CQCMDT = false -- If you use CQC MDT this will automatically send them to a players profile

**Comment by Intelligentzombie29** [comment]
this is my config for gabz mrpd, its working for me

**Comment by Quinn101** [comment]
Tested with Gabz MRPD appears to be working. Afraid this might be an issue on your end.
